# Generated by Django 4.2.6 on 2023-10-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الشرح'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الشرح'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='category',
            name='use_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الاستخدام'),
        ),
        migrations.AddField(
            model_name='category',
            name='use_en',
            field=models.TextField(blank=True, null=True, verbose_name='الاستخدام'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='الشرح'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='الشرح'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_ar',
            field=models.TextField(blank=True, null=True, verbose_name='المزايا'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_en',
            field=models.TextField(blank=True, null=True, verbose_name='المزايا'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='الاسم'),
        ),
    ]
