# Generated by Django 4.2.6 on 2023-10-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_options_category_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image1',
            field=models.ImageField(upload_to='categories/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image2',
            field=models.ImageField(upload_to='categories/%Y-%m-%d'),
        ),
    ]
