# Generated by Django 4.2.6 on 2023-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_category_alter_category_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.TextField(blank=True, verbose_name='التطبيقات'),
        ),
        migrations.AddField(
            model_name='product',
            name='applications_ar',
            field=models.TextField(blank=True, null=True, verbose_name='التطبيقات'),
        ),
        migrations.AddField(
            model_name='product',
            name='applications_en',
            field=models.TextField(blank=True, null=True, verbose_name='التطبيقات'),
        ),
    ]
