# Generated by Django 4.2.6 on 2023-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_applications_product_applications_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company-profile', verbose_name='صورة')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('profile', models.TextField(verbose_name='عن الشركة')),
                ('description_about', models.TextField(blank=True, verbose_name='المزيد عن الشركة (يعرض في صفحة المزيد)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الشخص')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='الوظيفة')),
                ('image', models.ImageField(upload_to='team', verbose_name='الصورة')),
            ],
        ),
    ]
