# Generated by Django 4.2.6 on 2023-10-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_companyimage_companyprofile_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.companyprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description_about_ar',
            field=models.TextField(blank=True, null=True, verbose_name='المزيد عن الشركة (يعرض في صفحة المزيد)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description_about_en',
            field=models.TextField(blank=True, null=True, verbose_name='المزيد عن الشركة (يعرض في صفحة المزيد)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='profile_ar',
            field=models.TextField(null=True, verbose_name='عن الشركة'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='profile_en',
            field=models.TextField(null=True, verbose_name='عن الشركة'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='title_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.companyprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='اسم الشخص'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='اسم الشخص'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='الوظيفة'),
        ),
    ]
