# Generated by Django 4.2.6 on 2023-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_companyimage_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(max_length=50, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='الوظيفة'),
        ),
    ]
