# Generated by Django 4.2.6 on 2023-10-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_companyprofile_chat_me_companyprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': 'Company Profile'},
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='pdf',
            field=models.URLField(default=' ', verbose_name='رابط ملف الpdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='gmail',
            field=models.EmailField(max_length=254, verbose_name='الإيميل'),
        ),
    ]
