# Generated by Django 4.2.6 on 2023-11-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_companyprofile_options_companyprofile_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_full',
            field=models.TextField(blank=True, verbose_name='التفاصيل'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_full_ar',
            field=models.TextField(blank=True, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_full_en',
            field=models.TextField(blank=True, null=True, verbose_name='التفاصيل'),
        ),
    ]
